# Aprendizagem - Homework III
### II. Programming - Grupo99
(ist1106059, ist1106329)

1- 

In [35]:
import numpy as np

X = np.array([[1,1],[1,3], [1,6],[1,9], [1,8]])
Z = np.array([[1.25],[7.0],[2.7],[3.2],[5.5]])
Xt =  np.transpose(X)

XtX = Xt @ X
I = np.identity(2)

XtXIinv = np.linalg.inv(XtX+I)

resultado = XtXIinv @ Xt @ Z

print("Inversa de A:\n")
print(XtXIinv)
print("\n\nResultado da multiplicação da inversa de A por B:\n")
print(resultado)

Inversa de A:

[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]


Resultado da multiplicação da inversa de A por B:

[[1.81808511]
 [0.32375887]]


In [42]:
#Simples multiplicação de matrizes
m1=np.array([[1,1],[1,3],[1,6],[1,9],[1,8]])
m2=np.array([1.81809, 0.32376])
print(m1 @ m2)

[2.14185 2.78937 3.76065 4.73193 4.40817]


In [38]:
#forward propagation
from scipy.special import softmax

X0 = np.array([[1],[1]])
W1 = np.array([[0.1, 0.1],[0.1, 0.2],[0.2,0.1]])
b1 = np.array([[0.1], [0], [0.1]])
W2 = np.array([[1,2,2],[1,2,1],[1,1,1]])
b2 = np.array([[1],[1],[1]])

Z1=W1 @ X0 + b1
X1=Z1
print(f"x1:\n\n{X1}")

Z2=W2 @ X1 + b2
X2=softmax(Z2)
print(f"\nz2:\n\n{Z2}")
print(f"\nx2:\n\n{X2}")

x1:

[[0.3]
 [0.3]
 [0.4]]

z2:

[[2.7]
 [2.3]
 [2. ]]

x2:

[[0.46148762]
 [0.3093444 ]
 [0.22916797]]


In [43]:
#update w e b
W2_old=np.array([[1,2,2],[1,2,1],[1,1,1]])
B2_old=np.array([[1],[1],[1]])
delta2 = X2 - np.array([[0],[1],[0]])

print("delta:\n")
print(delta2)
print("\n\ndE/dx2:\n")
print(delta2 @ np.transpose(X1))
print("\n\nW2:\n")
print(W2_old - 0.1 * (delta2 @ np.transpose(X1)))
print("\n\nb2:\n")
print(B2_old - 0.1 * delta2)

delta:

[[ 0.46148762]
 [-0.6906556 ]
 [ 0.22916797]]


dE/dx2:

[[ 0.13844629  0.13844629  0.18459505]
 [-0.20719668 -0.20719668 -0.27626224]
 [ 0.06875039  0.06875039  0.09166719]]


W2:

[[0.98615537 1.98615537 1.9815405 ]
 [1.02071967 2.02071967 1.02762622]
 [0.99312496 0.99312496 0.99083328]]


b2:

[[0.95385124]
 [1.06906556]
 [0.9770832 ]]


In [44]:
#update w e b
W1_old=np.array([[0.1,0.1],[0.1,0.2],[0.2,0.1]])
W2_old=np.array([[1,1,1],[2,2,1],[2,1,1]])
B_old=np.array([[0.1],[0],[0.1]])
X0 = np.array([[1],[1]])

delta1 = W2_old @ delta2
print(f"delta 1:\n\n{delta1}")
print(delta1 @ np.transpose(X0))
print("\n\nW 1 new:\n")
print(W1_old - 0.1 * (delta1 @ np.transpose(X0)))
print("\n\nb 1 new:\n")
print(B_old - 0.1 * delta1)

delta 1:

[[-2.77555756e-17]
 [-2.29167972e-01]
 [ 4.61487623e-01]]
[[-2.77555756e-17 -2.77555756e-17]
 [-2.29167972e-01 -2.29167972e-01]
 [ 4.61487623e-01  4.61487623e-01]]


W 1 new:

[[0.1        0.1       ]
 [0.1229168  0.2229168 ]
 [0.15385124 0.05385124]]


b 1 new:

[[0.1       ]
 [0.0229168 ]
 [0.05385124]]
