# Aprendizagem - Homework III
### II. Programming - Grupo99
(ist1106059, ist1106329)

1- 

In [ ]:
import numpy as np

X = np.array([[1,1],[1,3], [1,6],[1,9], [1,8]])
Z = np.array([[1.25],[7.0],[2.7],[3.2],[5.5]])
Xt =  np.transpose(X)

XtX = Xt @ X
I = np.identity(2)

XtXIinv = np.linalg.inv(XtX+I)

resultado = XtXIinv @ Xt @ Z

print("Inversa de A:")
print(XtXIinv)
print("Resultado da multiplicação da inversa de A por B:")
print(resultado)

Inversa de A:
[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]
Resultado da multiplicação da inversa de A por B:
[[1.81808511]
 [0.32375887]]


In [ ]:
#Simples multiplicação de matrizes
X=np.array([[1,4],[1,2],[1,5]])
Y=np.array([3.31593, 0.11372])
print(X @ Y)

[3.77081 3.54337 3.88453]


In [ ]:
#forward propagation
from scipy.special import softmax

X0 = np.array([1,1])
W1 = np.array([[0.1, 0.1],[0.1, 0.2],[0.2,0.1]])
b1 = np.array([0.1, 0, 0.1])
W2 = np.array([[1,2,2],[1,2,1],[1,1,1]])
b2 = np.array([1,1,1])

Z1=W1 @ X0 + b1
X1=Z1
print(X1)

Z2=W2 @ X1 + b2
X2=softmax(Z2)
print(Z2)
print(X2)

[0.3 0.3 0.4]
[2.7 2.3 2. ]
[0.46148762 0.3093444  0.22916797]


In [ ]:
#update w e b
W_old=np.array([[1,2,2],[1,2,1],[1,1,1]])
B_old=np.array([1,1,1])
delta=np.array([0.46149,-0.69066,0.22917])
X= np.array([0.3,0.3,0.4])

print(W_old - 0.1 * (delta @ np.transpose(X)))
print(B_old - 0.1 * delta)

[[0.9977083 1.9977083 1.9977083]
 [0.9977083 1.9977083 0.9977083]
 [0.9977083 0.9977083 0.9977083]]
[0.953851 1.069066 0.977083]


In [ ]:
#update w e b
W1_old=np.array([[0.1,0.1],[0.1,0.2],[0.2,0.1]])
W2_old=np.array([[1,2,2],[1,2,1],[1,1,1]])
B_old=np.array([0.1,0,0.1])
delta2=np.array([0.46149,-0.69066,0.22917])
X0 = np.array([0.3,0.3,0.4])

delta1 = np.transpose(W2_old) @ delta2
print(delta1)

print(W1_old - 0.1 * (delta1 @ np.transpose(X0)))
print(B_old - 0.1 * delta1)

[-2.77555756e-17 -2.29170000e-01  4.61490000e-01]
[[0.0884155 0.0884155]
 [0.0884155 0.1884155]
 [0.1884155 0.0884155]]
[0.1      0.022917 0.053851]
