# Aprendizagem - Homework III
### II. Programming - Grupo99
(ist1106059, ist1106329)

1- 

In [9]:
import numpy as np

X = np.array([[1,1],[1,3], [1,6],[1,9], [1,8]])
Z = np.array([[1.25],[7.0],[2.7],[3.2],[5.5]])
Xt =  np.transpose(X)

XtX = Xt @ X
I = np.identity(2)

XtXIinv = np.linalg.inv(XtX+I)

resultado = XtXIinv @ Xt @ Z

print("Inversa de A:")
print(XtXIinv)
print("Resultado da multiplicação da inversa de A por B:")
print(resultado)

#print(X @ resultado)

Inversa de A:
[[ 0.45390071 -0.06382979]
 [-0.06382979  0.0141844 ]]
Resultado da multiplicação da inversa de A por B:
[[1.81808511]
 [0.32375887]]


In [12]:
X=np.array([[1,4],[1,2],[1,5]])
Y=np.array([3.31593, 0.11372])
print(X @ Y)

[3.77081 3.54337 3.88453]
